## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [11]:
#1
import numpy as np
a = np.zeros((10, 10))
a[0] = 1
a[-1] = 1
a[:,0] = 1
a[:,-1] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [12]:
#2
a = np.array([0, 1, 2, 3, 4])
b = np.tile(a, (5, 1))
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [13]:
#3
a = np.array([[0.,1.], [1.,0.]])
b = np.tile(a, (4, 4))
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [14]:
#4
a = np.arange(0, 10, 1)
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [15]:
#5
rd = np.random.randn(5,5)
rd = (rd - np.mean(rd)) / np.std(rd)
rd

array([[-0.93314549,  0.10845012,  0.8562255 , -0.32354236, -2.2235693 ],
       [ 0.38264514,  0.37550484,  0.04384275, -0.41247694,  0.39081137],
       [-0.88817502, -0.79991596, -1.62314962, -0.85663891,  0.86685255],
       [ 0.3866979 ,  0.70893895, -0.89602774,  0.57433491,  0.83148834],
       [ 1.25465446,  1.41954485, -0.27350874,  2.17394758, -1.1437892 ]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [16]:
#6
rd = np.random.randn(10, 2)
rp = rd.copy()
for i in range(10):
    rp[i,0] = np.sqrt(rd[i,0]*rd[i,0]+rd[i,1]*rd[i,1])
    rp[i,1] = np.arctan(rd[i,1] / rd[i,0])
rd, rp

(array([[-0.99377089,  0.38676303],
        [-0.72741722, -0.39834932],
        [ 0.59569908, -0.56278588],
        [ 0.73896722, -0.09279953],
        [ 2.14668469, -0.58693976],
        [ 0.08501492, -0.9518948 ],
        [ 0.27902148, -1.01058882],
        [ 0.56804552,  1.02906059],
        [-0.23206053, -1.08158025],
        [-0.43430688, -1.01258873]]),
 array([[ 1.06637996, -0.37115049],
        [ 0.82934793,  0.50101528],
        [ 0.8195031 , -0.75699525],
        [ 0.74477131, -0.12492607],
        [ 2.22547825, -0.26689377],
        [ 0.95568365, -1.4817214 ],
        [ 1.04840009, -1.30140966],
        [ 1.17543244,  1.06641587],
        [ 1.10619525,  1.35944371],
        [ 1.1017978 ,  1.16562067]]))

 7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [17]:
#7
v = np.array([1,2,3,4,5])
v = v.repeat(4)
for i in range(20):
    if i % 4 != 0:
        v[i] = 0
[v[0:17]]

[array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])]

8. What are the result of the following expressions?

0 * np.nan
nan
np.nan == np.nan
False!
np.inf > np.nan
False!
np.nan - np.nan
nan!
np.nan in set([np.nan])
True!
0.3 == 3 * 0.1 
False!
(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [22]:
#8
print(0 * np.nan)
# 0 times not a number is not a number
print(np.nan == np.nan)
# Cause nan can be represented many numbers
print(np.inf > np.nan)
# nan can not be compared
print(np.nan - np.nan)
# nan - nan = nan
print(np.nan in set([np.nan]))
# The definition of set
print(0.3 == 3 * 0.1)
# It exists little error under float multiplication

nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)
nan
np.array(0) // np.array(0)
0
np.array([np.nan]).astype(int).astype(float)
-2.147484e+09

First guess a result, then print the result, and finally find why 

In [21]:
#9
print(np.array(0) / np.array(0))
# nan / nan = nan, it is based on the storation of float
print(np.array(0) // np.array(0))
# 
print(np.array([np.nan]).astype(int).astype(float))
# Type coercion from int to float and leads to represent the maximum of int

nan
0
[-2.14748365e+09]


C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.


ZeroDivisionError: integer division or modulo by zero